#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
source $OPENSHIFT_DATA_DIR//.rvm/scripts/rvm
rvm use 1.9.3
nohup bundle exec rackup $OPENSHIFT_REPO_DIR/config.ru -s thin -E production -o $OPENSHIFT_INTERNAL_IP -p $OPENSHIFT_INTERNAL_PORT > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
